<?php

/**
 * Test class for AndroidAppBadge.
 * Generated by PHPUnit on 2011-03-06 at 13:58:14.
 */
class AndroidAppBadgeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AndroidAppBadge
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		require_once 'C:\Users\Nicke\Documents\wordpress\wp-includes\plugin.php';
		require_once 'C:\Users\Nicke\Documents\wordpress\wp-includes\l10n.php';
		require_once 'C:\Users\Nicke\Documents\wordpress\wp-includes\load.php';
		require_once 'C:\Users\Nicke\workspace\Market Badges\android_market_badge.php';
    	
		define("WP_PLUGIN_DIR", 'C:\Users\Nicke\workspace\Market Badges');
		$this->object = new AndroidAppBadge;
    	$this->object->init();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAdminMenu().
     */
    public function testAdminMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAdminInit().
     */
    public function testAdminInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseQR().
     */
    public function testParseQR()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseApp().
     */
    public function testParseApp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetBadge().
     */
    public function testGetBadge()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCompatFallback().
     */
    public function testCompatFallback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSettingsPage().
     */
    public function testSettingsPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSectionCallback().
     */
    public function testSectionCallback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOptionCallbackLogin().
     */
    public function testOptionCallbackLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOptionCallbackPassword().
     */
    public function testOptionCallbackPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOptionCallbackDevice().
     */
    public function testOptionCallbackDevice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOptionCallbackCache().
     */
    public function testOptionCallbackCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOptionCallbackQR().
     */
    public function testOptionCallbackQR()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOptionCallbackDesign().
     */
    public function testOptionCallbackDesign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOptionCallbackBadgeLink().
     */
    public function testOptionCallbackBadgeLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
